config/routes.rb
Rails.application.routes.draw do
  root "authors#index"
  get 'about', to: "books#about"
  resources "authors", only: [:index, :show]
  # resources "publishers", only: [:index, :show]
  # resources "countries", only: [:index, :show]

  resources "books", only: [:index, :show] do
    collection do
      get 'search_results'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  validates :name, presence: true, length: {minimum: 2}
  paginates_per 5
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :publishers
  validates :title, presence: true, length: {minimum: 2}
  paginates_per 15
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :publishers
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  belongs_to :book
  belongs_to :country
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.page(params[:page])
  end

  def show
    @author = Author.find(params[:id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.includes(:author).order(:id).page(params[:page])
  end

  def show
    @book = Book.find(params[:id])
  end

  def search_results
    @books = Book.where( 'title LIKE ?', "%#{params[:query]}%" )
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/index.html.erb
<div class="container columns is-multiline" >
  <div class = "column">
    <h1>Authors - Collection</h1>
      <% if @authors.empty? %>
      <% else %>
        <% @authors.each do |author| %>
          <h2> <%= link_to author.name, author %> </h2>
          <p><%= author.name %> has written <%= pluralize(author.books.count, "book") %>.</p>
        <% end %>
        <nav class="pagination">
          <p>
            <%= paginate @authors %>
          </p>
        </nav>
      <% end %>
  </div>
</div>

app/views/authors/show.html.erb
<div class = "container">
  <h2>Books by <%= @author.name %></h2>

  <% if @author.books.empty? %>
    <p>There are no books written by <%= @author.name %></p>
  <% else %>
    <ul>
      <% @author.books.each do |book| %>
      <li> <%= link_to book.title, book %> </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/books/_search.html.erb
<%= form_with url: "/search", method: :get do |form| %>
  <%# <%= form.label :query, "Search for:" %>
  <%= form.text_field :query %>
  <%= form.submit "Search" %>
<% end %>

app/views/books/_searchform.html.erb
<%= form_with url: search_results_books_path, method: :get do |form| %>
  <%= form.text_field :query %>
  <%= form.select :category, ["Fiction", "Non-Fiction"] %>
  <%= form.submit "Search" %>
<% end %>

app/views/books/about.html.erb
<h1>About the Application</h1>
<p>This website displays lists of books, authors, publishers, and countries. <br/>
Detailed information is available on each book, author, publisher, and country. </p>
<h4>Git Repository</h4>
<p>A git respository is a piece-wise record of the steps taken to develop an application. <br/>
The git repository for this project can be found here:</p>
<%= link_to "https://github.com/marissa-steindel/DataDrivenRailsProject.git", "https://github.com/marissa-steindel/DataDrivenRailsProject.git" %>

<h3>Dataset Description</h3>
<p>The dataset used for this Data-Driven Rails Application is comprised of a CSV (Comma Separated List) and Data generated by the Faker gem.</p>
<p>The CSV contains the columns: Title, Author, SubGenre, Height, and Publisher. Some records are missing an author, so Faker data will be generated in its place.</p>
<p>The database will be comprised of tables: Authors, Books, Publishers, and Countries.
The Entity Relationship Diagram (ERD) below specifies the columns of each table.</p>

<h3>Dataset Relationships</h3>
<p>An author has many books. A book belongs to an author.<br/>
A book has one publisher.<br/>
A publisher belongs to one country. A country can have many publishers.</p>

<h3>Database Entity Relationship Diagram</h3>
<%= image_tag "erd.JPG" %>

app/views/books/index.html.erb
<div class="container columns is-multiline" >
  <div class="column">
      <h1>All Books - Collection</h1>

      <% if @books.empty? %>
        <p>There are no books.</p>
      <% else %>
        <ul>
          <% @books.each do |book| %>
            <li> <%= link_to book.title, book_path(book) %> by <%= link_to book.author.name, book.author %></li>
          <% end %>
        </ul>
      <% end %>

      <nav class="pagination">
        <p>
          <%= paginate @books %>
        </p>
      </nav>
  </div>
</div>

app/views/books/search_results.html.erb
<h1>Search Results</h1>

<p>You searched for '<%= params[:query] %>'.</p>
<p><%= pluralize(@books.size, "result")%> found.</p>

<% if @books.empty? %>
  <p>No books found.</p>
<% else %>
  <ul>
    <% @books.each do |book| %>
      <li> <%= link_to book.title, book %> </li>
    <% end %>
  </ul>
<% end %>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-sm-6">
      <%# <p>insert image here</p> %>
    </div>
    <div class="col">
      <h2 class="mb-3"><%= @book.title %></h2>
      <p><strong>Author:</strong> <%= link_to @book.author.name, author_path(@book.author) %></p>
      <p><strong>Synopsis:</strong> <%= @book.synopsis %></p>
      <p><strong>Number of pages:</strong> <%= @book.pages %></p>
      <p><strong>Genre:</strong> <%= @book.genre %></p>
      <p><strong>Publisher:</strong> <%= Faker::Book.publisher %></p>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<%# <%= render "layouts/pagination"  %>

<footer class="footer has-background-link has-text-white">
  <div class="content has-text-centered">
    <p>Web Development by Marissa Steindel</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<section class="hero is-small is-link">
  <div class="hero-body">
    <h1 class="title"><%= link_to "Data-Driven Rails Application", root_path %></h1>
  </div>
</section>

<div class="tabs is-medium">
  <ul>
    <li><%= link_to "Home", root_path%></li>
    <li><%= link_to "About", about_path%></li>
    <li><%= link_to "Authors", root_path%></li>
    <li><%= link_to "Books", books_path %></li>
    <li><%= link_to "Publishers", "#" %></li>
    <li><%= render partial: "books/searchform" %></li>
  </ul>
</div>

app/views/layouts/_pagination.html.erb
<div class="section">

  <nav class="pagination is-rounded" role="navigation" aria-label="pagination">

    <a class="pagination-previous">Previous</a>
    <a class="pagination-next">Next page</a>

    <ul class="pagination-list">
      <li><a class="pagination-link" aria-label="Goto page 1">1</a></li>
      <li><span class="pagination-ellipsis">&hellip;</span></li>
      <li><a class="pagination-link" aria-label="Goto page 45">45</a></li>
      <li><a class="pagination-link is-current" aria-label="Page 46" aria-current="page">46</a></li>
      <li><a class="pagination-link" aria-label="Goto page 47">47</a></li>
      <li><span class="pagination-ellipsis">&hellip;</span></li>
      <li><a class="pagination-link" aria-label="Goto page 86">86</a></li>
    </ul>

  </nav>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataDrivenRailsProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%# <!-- Bootstrap CDN - content delivery network -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script> %>

    <!-- Bulma CDN - content delivery network -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">

  </head>

  <body>
    <%= render partial: "layouts/header" %>

    <section class="section">
      <div class="content">
        <%= yield %>
      </div>
    </section>

    <%= render partial: "layouts/footer" %>
</body>
</html>